/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdmissionsRouteImport } from './routes/_authenticated/admissions'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedConsultationsRouteImport } from './routes/_authenticated/consultations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFrontDeskRouteImport } from './routes/_authenticated/front-desk'
import { Route as AuthenticatedHospitalSetupRouteImport } from './routes/_authenticated/hospital-setup'
import { Route as AuthenticatedLabRouteImport } from './routes/_authenticated/lab'
import { Route as AuthenticatedMaternityRouteImport } from './routes/_authenticated/maternity'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedRadiologyRouteImport } from './routes/_authenticated/radiology'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTransfersRouteImport } from './routes/_authenticated/transfers'
import { Route as AuthenticatedTriageRouteImport } from './routes/_authenticated/triage'
import { Route as AuthenticatedWardsRouteImport } from './routes/_authenticated/wards'
import { Route as HospitalsHospitalSlugRouteImport } from './routes/hospitals/$hospitalSlug'
import { Route as AuthenticatedAppointmentsIndexRouteImport } from './routes/_authenticated/appointments/index'
import { Route as AuthenticatedAppointmentsQueueRouteImport } from './routes/_authenticated/appointments/queue'
import { Route as AuthenticatedBillingIndexRouteImport } from './routes/_authenticated/billing/index'
import { Route as AuthenticatedPatientsIndexRouteImport } from './routes/_authenticated/patients/index'
import { Route as AuthenticatedPatientsPatientIdRouteImport } from './routes/_authenticated/patients/$patientId'
import { Route as AuthenticatedPharmacyIndexRouteImport } from './routes/_authenticated/pharmacy/index'
import { Route as AuthenticatedPharmacyInventoryRouteImport } from './routes/_authenticated/pharmacy/inventory'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdmissionsRoute = AuthenticatedAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsultationsRoute =
  AuthenticatedConsultationsRouteImport.update({
    id: '/consultations',
    path: '/consultations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFrontDeskRoute = AuthenticatedFrontDeskRouteImport.update({
  id: '/front-desk',
  path: '/front-desk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHospitalSetupRoute =
  AuthenticatedHospitalSetupRouteImport.update({
    id: '/hospital-setup',
    path: '/hospital-setup',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLabRoute = AuthenticatedLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaternityRoute = AuthenticatedMaternityRouteImport.update({
  id: '/maternity',
  path: '/maternity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRadiologyRoute = AuthenticatedRadiologyRouteImport.update({
  id: '/radiology',
  path: '/radiology',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransfersRoute = AuthenticatedTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTriageRoute = AuthenticatedTriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWardsRoute = AuthenticatedWardsRouteImport.update({
  id: '/wards',
  path: '/wards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const HospitalsHospitalSlugRoute = HospitalsHospitalSlugRouteImport.update({
  id: '/hospitals/$hospitalSlug',
  path: '/hospitals/$hospitalSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppointmentsIndexRoute =
  AuthenticatedAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppointmentsQueueRoute =
  AuthenticatedAppointmentsQueueRouteImport.update({
    id: '/appointments/queue',
    path: '/appointments/queue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingIndexRoute =
  AuthenticatedBillingIndexRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientsIndexRoute =
  AuthenticatedPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientsPatientIdRoute =
  AuthenticatedPatientsPatientIdRouteImport.update({
    id: '/patients/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPharmacyIndexRoute =
  AuthenticatedPharmacyIndexRouteImport.update({
    id: '/pharmacy/',
    path: '/pharmacy/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPharmacyInventoryRoute =
  AuthenticatedPharmacyInventoryRouteImport.update({
    id: '/pharmacy/inventory',
    path: '/pharmacy/inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admissions': typeof AuthenticatedAdmissionsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/consultations': typeof AuthenticatedConsultationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/front-desk': typeof AuthenticatedFrontDeskRoute
  '/hospital-setup': typeof AuthenticatedHospitalSetupRoute
  '/lab': typeof AuthenticatedLabRoute
  '/maternity': typeof AuthenticatedMaternityRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/radiology': typeof AuthenticatedRadiologyRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/triage': typeof AuthenticatedTriageRoute
  '/wards': typeof AuthenticatedWardsRoute
  '/hospitals/$hospitalSlug': typeof HospitalsHospitalSlugRoute
  '/appointments/queue': typeof AuthenticatedAppointmentsQueueRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/pharmacy/inventory': typeof AuthenticatedPharmacyInventoryRoute
  '/appointments/': typeof AuthenticatedAppointmentsIndexRoute
  '/billing/': typeof AuthenticatedBillingIndexRoute
  '/patients/': typeof AuthenticatedPatientsIndexRoute
  '/pharmacy/': typeof AuthenticatedPharmacyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admissions': typeof AuthenticatedAdmissionsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/consultations': typeof AuthenticatedConsultationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/front-desk': typeof AuthenticatedFrontDeskRoute
  '/hospital-setup': typeof AuthenticatedHospitalSetupRoute
  '/lab': typeof AuthenticatedLabRoute
  '/maternity': typeof AuthenticatedMaternityRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/radiology': typeof AuthenticatedRadiologyRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/triage': typeof AuthenticatedTriageRoute
  '/wards': typeof AuthenticatedWardsRoute
  '/hospitals/$hospitalSlug': typeof HospitalsHospitalSlugRoute
  '/appointments/queue': typeof AuthenticatedAppointmentsQueueRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/pharmacy/inventory': typeof AuthenticatedPharmacyInventoryRoute
  '/appointments': typeof AuthenticatedAppointmentsIndexRoute
  '/billing': typeof AuthenticatedBillingIndexRoute
  '/patients': typeof AuthenticatedPatientsIndexRoute
  '/pharmacy': typeof AuthenticatedPharmacyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admissions': typeof AuthenticatedAdmissionsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/consultations': typeof AuthenticatedConsultationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/front-desk': typeof AuthenticatedFrontDeskRoute
  '/_authenticated/hospital-setup': typeof AuthenticatedHospitalSetupRoute
  '/_authenticated/lab': typeof AuthenticatedLabRoute
  '/_authenticated/maternity': typeof AuthenticatedMaternityRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/radiology': typeof AuthenticatedRadiologyRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/transfers': typeof AuthenticatedTransfersRoute
  '/_authenticated/triage': typeof AuthenticatedTriageRoute
  '/_authenticated/wards': typeof AuthenticatedWardsRoute
  '/hospitals/$hospitalSlug': typeof HospitalsHospitalSlugRoute
  '/_authenticated/appointments/queue': typeof AuthenticatedAppointmentsQueueRoute
  '/_authenticated/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/_authenticated/pharmacy/inventory': typeof AuthenticatedPharmacyInventoryRoute
  '/_authenticated/appointments/': typeof AuthenticatedAppointmentsIndexRoute
  '/_authenticated/billing/': typeof AuthenticatedBillingIndexRoute
  '/_authenticated/patients/': typeof AuthenticatedPatientsIndexRoute
  '/_authenticated/pharmacy/': typeof AuthenticatedPharmacyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admissions'
    | '/audit'
    | '/consultations'
    | '/dashboard'
    | '/front-desk'
    | '/hospital-setup'
    | '/lab'
    | '/maternity'
    | '/portal'
    | '/radiology'
    | '/referrals'
    | '/reports'
    | '/settings'
    | '/team'
    | '/transfers'
    | '/triage'
    | '/wards'
    | '/hospitals/$hospitalSlug'
    | '/appointments/queue'
    | '/patients/$patientId'
    | '/pharmacy/inventory'
    | '/appointments/'
    | '/billing/'
    | '/patients/'
    | '/pharmacy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admissions'
    | '/audit'
    | '/consultations'
    | '/dashboard'
    | '/front-desk'
    | '/hospital-setup'
    | '/lab'
    | '/maternity'
    | '/portal'
    | '/radiology'
    | '/referrals'
    | '/reports'
    | '/settings'
    | '/team'
    | '/transfers'
    | '/triage'
    | '/wards'
    | '/hospitals/$hospitalSlug'
    | '/appointments/queue'
    | '/patients/$patientId'
    | '/pharmacy/inventory'
    | '/appointments'
    | '/billing'
    | '/patients'
    | '/pharmacy'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admissions'
    | '/_authenticated/audit'
    | '/_authenticated/consultations'
    | '/_authenticated/dashboard'
    | '/_authenticated/front-desk'
    | '/_authenticated/hospital-setup'
    | '/_authenticated/lab'
    | '/_authenticated/maternity'
    | '/_authenticated/portal'
    | '/_authenticated/radiology'
    | '/_authenticated/referrals'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/transfers'
    | '/_authenticated/triage'
    | '/_authenticated/wards'
    | '/hospitals/$hospitalSlug'
    | '/_authenticated/appointments/queue'
    | '/_authenticated/patients/$patientId'
    | '/_authenticated/pharmacy/inventory'
    | '/_authenticated/appointments/'
    | '/_authenticated/billing/'
    | '/_authenticated/patients/'
    | '/_authenticated/pharmacy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  HospitalsHospitalSlugRoute: typeof HospitalsHospitalSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admissions': {
      id: '/_authenticated/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AuthenticatedAdmissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consultations': {
      id: '/_authenticated/consultations'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof AuthenticatedConsultationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/front-desk': {
      id: '/_authenticated/front-desk'
      path: '/front-desk'
      fullPath: '/front-desk'
      preLoaderRoute: typeof AuthenticatedFrontDeskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hospital-setup': {
      id: '/_authenticated/hospital-setup'
      path: '/hospital-setup'
      fullPath: '/hospital-setup'
      preLoaderRoute: typeof AuthenticatedHospitalSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lab': {
      id: '/_authenticated/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof AuthenticatedLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maternity': {
      id: '/_authenticated/maternity'
      path: '/maternity'
      fullPath: '/maternity'
      preLoaderRoute: typeof AuthenticatedMaternityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/radiology': {
      id: '/_authenticated/radiology'
      path: '/radiology'
      fullPath: '/radiology'
      preLoaderRoute: typeof AuthenticatedRadiologyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transfers': {
      id: '/_authenticated/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AuthenticatedTransfersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/triage': {
      id: '/_authenticated/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof AuthenticatedTriageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wards': {
      id: '/_authenticated/wards'
      path: '/wards'
      fullPath: '/wards'
      preLoaderRoute: typeof AuthenticatedWardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/hospitals/$hospitalSlug': {
      id: '/hospitals/$hospitalSlug'
      path: '/hospitals/$hospitalSlug'
      fullPath: '/hospitals/$hospitalSlug'
      preLoaderRoute: typeof HospitalsHospitalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/appointments/': {
      id: '/_authenticated/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AuthenticatedAppointmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments/queue': {
      id: '/_authenticated/appointments/queue'
      path: '/appointments/queue'
      fullPath: '/appointments/queue'
      preLoaderRoute: typeof AuthenticatedAppointmentsQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing/': {
      id: '/_authenticated/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof AuthenticatedBillingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients/': {
      id: '/_authenticated/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthenticatedPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients/$patientId': {
      id: '/_authenticated/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pharmacy/': {
      id: '/_authenticated/pharmacy/'
      path: '/pharmacy'
      fullPath: '/pharmacy/'
      preLoaderRoute: typeof AuthenticatedPharmacyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pharmacy/inventory': {
      id: '/_authenticated/pharmacy/inventory'
      path: '/pharmacy/inventory'
      fullPath: '/pharmacy/inventory'
      preLoaderRoute: typeof AuthenticatedPharmacyInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdmissionsRoute: typeof AuthenticatedAdmissionsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedConsultationsRoute: typeof AuthenticatedConsultationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFrontDeskRoute: typeof AuthenticatedFrontDeskRoute
  AuthenticatedHospitalSetupRoute: typeof AuthenticatedHospitalSetupRoute
  AuthenticatedLabRoute: typeof AuthenticatedLabRoute
  AuthenticatedMaternityRoute: typeof AuthenticatedMaternityRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedRadiologyRoute: typeof AuthenticatedRadiologyRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTransfersRoute: typeof AuthenticatedTransfersRoute
  AuthenticatedTriageRoute: typeof AuthenticatedTriageRoute
  AuthenticatedWardsRoute: typeof AuthenticatedWardsRoute
  AuthenticatedAppointmentsQueueRoute: typeof AuthenticatedAppointmentsQueueRoute
  AuthenticatedPatientsPatientIdRoute: typeof AuthenticatedPatientsPatientIdRoute
  AuthenticatedPharmacyInventoryRoute: typeof AuthenticatedPharmacyInventoryRoute
  AuthenticatedAppointmentsIndexRoute: typeof AuthenticatedAppointmentsIndexRoute
  AuthenticatedBillingIndexRoute: typeof AuthenticatedBillingIndexRoute
  AuthenticatedPatientsIndexRoute: typeof AuthenticatedPatientsIndexRoute
  AuthenticatedPharmacyIndexRoute: typeof AuthenticatedPharmacyIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdmissionsRoute: AuthenticatedAdmissionsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedConsultationsRoute: AuthenticatedConsultationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFrontDeskRoute: AuthenticatedFrontDeskRoute,
  AuthenticatedHospitalSetupRoute: AuthenticatedHospitalSetupRoute,
  AuthenticatedLabRoute: AuthenticatedLabRoute,
  AuthenticatedMaternityRoute: AuthenticatedMaternityRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedRadiologyRoute: AuthenticatedRadiologyRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTransfersRoute: AuthenticatedTransfersRoute,
  AuthenticatedTriageRoute: AuthenticatedTriageRoute,
  AuthenticatedWardsRoute: AuthenticatedWardsRoute,
  AuthenticatedAppointmentsQueueRoute: AuthenticatedAppointmentsQueueRoute,
  AuthenticatedPatientsPatientIdRoute: AuthenticatedPatientsPatientIdRoute,
  AuthenticatedPharmacyInventoryRoute: AuthenticatedPharmacyInventoryRoute,
  AuthenticatedAppointmentsIndexRoute: AuthenticatedAppointmentsIndexRoute,
  AuthenticatedBillingIndexRoute: AuthenticatedBillingIndexRoute,
  AuthenticatedPatientsIndexRoute: AuthenticatedPatientsIndexRoute,
  AuthenticatedPharmacyIndexRoute: AuthenticatedPharmacyIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  HospitalsHospitalSlugRoute: HospitalsHospitalSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
